name: go-test

on:
  push:
    paths:
      - "**/*.go"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**/*.go"
      - ".github/workflows/ci.yml"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Go Module
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Dependencies
        run: go get -v -t -d ./...
      - name: Go test
        run: go test -v ./...
